default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: survey_cat_development

test:
  <<: *default
  database: survey_cat_test

production:
  <<: *default
  database: survey_cat_production
  username: survey_cat
  password: <%= ENV['SURVEY_FALCON_DATABASE_PASSWORD'] %>
