# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fddae7c5fa09c88ae8d5dade3cf129f4e1c1b84ab8b73afc66e233cbcc12ec7df7af03121abe6bdb3c5658b46c374a0304b65e00b6e33d54b26b778e965062e

test:
  secret_key_base: 09f3dc0a1c6f728692991876a264cb697be095faebc6961d2b228b321712e06f013bc0efcab352faaa8f0e052e029eac7907039279693bed616e39cb37c628b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
